name: CI/CD Web Login

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for HTML Errors
        run: test -f frontend/index.html || exit 1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./frontend" # ระบุโฟลเดอร์ที่เก็บไฟล์ HTML/CSS/JS

  deploy:
    needs: build # ต้องรอให้ build เสร็จก่อน
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4